### ISSUE TITLE
VT-x error

### ISSUE THREAD

**Issue by dr3nkrypted** [H21lab/tsharkVM#1]
<img width="1055" alt="Screen Shot 2020-09-04 at 3 32 45 PM" src="https://user-images.githubusercontent.com/68912706/92282783-f5e9e000-eec3-11ea-97d4-b308572a9ebf.png">

Receiving this error with startvm.

**Comment by H21lab** [comment]
This seems to be related to your host and VirtualBox. Here are possible options to resolve this:
- You can enable the virtualization in the BIOS to get VT-x support if your CPU is supporting this
- Or open VirtualBox and edit the settings of that created VM  (System -> Processor -> Disable Nested VT-x / AMD-V). Or use vboxmanage to disable it (`VBoxManage modifyvm <VM_NAME> --vtxvpid off`)
- Or you can change vagrant file and rebuild VM without VT-x support (https://gist.github.com/betweenbrain/7798873)
