### ISSUE TITLE
Suggestion file tags!

### ISSUE THREAD

**Issue by priamai** [H21lab/tsharkVM#5]
Let me explain first, I need to replay a lot of PCAPS from different systems and time periods. The problem is then to find all the packets related to a specific pcap file name.
It would be very helpful to have a way to add a field which contains the PCAP file name.
I have looked at the way the logstash pipeline works and I don't believe there is an easy way to achieve that because it is just receiving the pcap on the tcp socket.

I am wondering if there is an alternative way via logstash to capture the input file name maybe via http POST (which should contain that)?

**Comment by priamai** [comment]
There were some other ideas here from an old post: https://www.elastic.co/blog/analyzing-network-packets-with-wireshark-elasticsearch-and-kibana suggesting filebeat or simple bulk api to ingest but of course we will loose the processing steps with logstash.

**Comment by H21lab** [comment]
Thank you for this suggestion. This is limitation in the current code.

Code (in [`tshark_logstash.conf`](https://github.com/H21lab/tsharkVM/blob/6bbdb70b158c3817476e82491c58cc4a852ab2c0/Public/tshark_logstash.conf#L18)) uses logstash [Tcp input plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html). The jsons are streamed to the logstash TCP socket so the filenames are not kept.

To keep the filenames, the logstash [File input plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html) could be used to read the tshark jsons from folder. 

This can be achieved by changing the input plugin (in [`tshark_logstash.conf`](https://github.com/H21lab/tsharkVM/blob/6bbdb70b158c3817476e82491c58cc4a852ab2c0/Public/tshark_logstash.conf#L18)) or by having multiple logstash pipelines. One reading from socket and second reading from the files.

**Comment by robomotic** [comment]
Yes correct, question does the tshark JSON output file contain the filename ? If it does would be fairly easy, I can do a quick check later.

**Comment by H21lab** [comment]
tshark ndjson does not include the filename. You can check it by running `tshark -T ek -r ./Traces/dhcp-and-dyndns.pcap.gz`

**Comment by robomotic** [comment]
Quick idea, a simple script to add a field in the intermediate JSON file? Should be able even without python maybe.

**Comment by H21lab** [comment]
Yes, maybe it can work, but it would add some pre-processing. The easier approach seems to change the logstash input plugin (in [tshark_logstash.conf](https://github.com/H21lab/tsharkVM/blob/6bbdb70b158c3817476e82491c58cc4a852ab2c0/Public/tshark_logstash.conf#L18)): 
- Use [File input plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html) to read the ndjson files from folder instead of reading from socket
- The tshark should dump the files to this folder and not to the socket
- The processed ndjsons could be directly deleted by [`file_completed_action`](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-file_completed_action)

**Comment by priamai** [comment]
I like your approach better and it could just be a shared folder in Vagrant or a writable volume if using Docker.
If you want to try it I can be your test subject!

**Comment by H21lab** [comment]
Here is the patch daedd3c1a30fdb877780a40a81e806621fb6f7bf. This is using an another logstash pipeline reading files from /home/vagrant/input/*.ndjson.  And the old method is working too, two logstash pipelines are running in parallel (see `/etc/logstash/conf.d/`).

You have to rebuilt the VM to use it and install also `vagrant plugin install vagrant-scp`. And after use `bash upload_pcaps_with_filenames.sh`.

**Comment by priamai** [comment]
Testing now.

**Comment by priamai** [comment]
Wonderful is working now and the input file plugin add automatically the path field.
I only have one issue with this bash line:

```
robomotic@TsharkVM:~/tsharkVM$ find ./Traces/ -type f -not -name "*.md" -exec bash -c "tshark -r {} -T ek > ./VM/{}.ndjson" \;
bash: ./VM/./Traces/dhcp-and-dyndns.pcap.gz.ndjson: No such file or directory
```
The problem is that the {} argument takes the entire folder path from my understanding. 
There should be a way in bash to take just the filename?

**Comment by H21lab** [comment]
I just updated the following line: https://github.com/H21lab/tsharkVM/blob/97243a4f08550139bee534e1b34dc1cc1770b1e3/upload_pcaps_with_filenames.sh#L20
Let me know if it works for you.

**Comment by priamai** [comment]
Wonderful is working!
