### ISSUE TITLE
need a license to use this

### ISSUE THREAD

**Issue by jgao1025** [H21lab/tsharkVM#6]
I just tried this but ELK is using a commercial version. Do you have any plan to use oss verson? Thanks.

**Comment by jgao1025** [comment]
I was able to ssh to vm and changed to install oss version, but I got

“Format version is not supported”

when I restarted elasticsearch service. It's not a easy fix for me.

**Comment by H21lab** [comment]
You can use basic license https://www.elastic.co/subscriptions. 

For Apache license, some modifications would be needed in current code and in Kibana vizualizations.
Elastic seems to be moving away from Apache license https://www.elastic.co/pricing/faq/licensing.

**Comment by jgao1025** [comment]
> You can use basic license https://www.elastic.co/subscriptions.
> 
> For Apache license, some modifications would be needed in current code and in Kibana vizualizations. Elastic seems to be moving away from Apache license https://www.elastic.co/pricing/faq/licensing.

Okay. Thanks for the information. I will try that.

I still prefer open sourced software so I would probably work on this if I can find this is useful to me.
